### ISSUE TITLE
Be more clear about purpose

### ISSUE THREAD

**Issue by dpriskorn** [civictechsweden/JagVillHaVaccin#16]
Hi
Today the purpose of the page is in the bottom of the about site. It seems at least one employee https://www.svt.se/nyheter/lokalt/blekinge/regionen-avrader-anvandning-av-ny-bokningssida has misunderstood the purpose of the website.
I suggest to clearly state the purpose in the top of the about page.
Something like
"Syftet med denna webbplats är att avlasta regionernas infrastruktur och endast visa var det finns lediga tider.
Målet är att öka effektivteten i vården och att folk ska slippa logga in bara för att se om det finns en ledig tid.

Det är således en användarvänlig tjänst som också är bra för regionerna för de i bästa fall slipper anstormning av folk efter att de öppnat nya kvoter för vaccinering"

**Comment by dpriskorn** [comment]
this belong in the other repo

**Comment by PierreMesure** [comment]
Hi @dpriskorn, I am closing this issue since no one is working on it. I think your points were addressed as the texts on the website were substantially improved these past few weeks.
