### ISSUE TITLE
Implement temporary solution for VGR

### ISSUE THREAD

**Issue by peterk** [civictechsweden/JagVillHaVaccin#2]
Until the official API is released, implement a temporary web scraping solution for Västra götalandsregionen (VGR)

**Comment by PierreMesure** [comment]
I would prefer to wait as the webpage shows data in a different format (">100 doser" instead of the exact amount, no date) so that would be require adapting the frontend to this new data.

Apparently, the API will be closer to VMD's format. (see #3)

**Comment by PierreMesure** [comment]
The API is now used to fetch data from VGR but I'll leave this issue open as VGR is showing more data through its page than its API... 😅

**Comment by PierreMesure** [comment]
Now I also implemented fetching from the webpage although the data is not used by JVHV yet.
