### ISSUE TITLE
Import data from Region Västra Götaland's upcoming API

### ISSUE THREAD

**Issue by marcusosterberg** [civictechsweden/JagVillHaVaccin#3]
This is a preview of how the first edition of Region Västra Götaland's API will output data:
[vaccine-2021-05-25.txt](https://github.com/civictechsweden/JagVillHaVaccin/files/6542000/vaccine-2021-05-25.txt)

The website itself can be accessed here: https://www.vgregion.se/ov/vaccinationstider/bokningsbara-tider/

**Comment by marcusosterberg** [comment]
Example vaccination unit:
`"title": "Närhälsan Furulund vårdcentral",
 "hsaid": "SE2321000131-E000000004567",
"municipality": "1402",
"urlBooking": "https://e-tjanster.1177.se/mvk/scheduling/tbMakeValidation.xhtml?hsaid=SE2321000131-E000000004567&dynamicid=bb0225fc-7c37-47c1-8558-ddb991501c2c",
"urlContactCard": "https://www.1177.se/Vastra-Gotaland/hitta-vard/kontaktkort/Narhalsan-Furulund-vardcentral-Partille/",
"urlContactCardText": "1",
"testtype": "1",
"timeslots": 0,
"updated": "2021-05-25 20:57:12"`

Explanation
* title: Name of the vaccination unit
* hsaid: unique ID for the vaccination unit
* municipality: integer for the [municipality's code according to SKR](https://catalog.skl.se/catalog/1/datasets/50)
* urlBooking: URL to reserve a vaccination appointment
* urlContactCard: URL to the vaccination unit's info on 1177.se
* urlContactCardText: n/a for non-VGR
* testtype: n/a for non-VGR
* timeslots: integer, sometimes null for 0/unknown
* updated: yyyy-mm-dd hh:mm:ss, when we last checked timeslots against our integration platform

**Comment by PierreMesure** [comment]
Really cool! Thank you for posting it here!

**Comment by PierreMesure** [comment]
The API support has been added [here](https://github.com/civictechsweden/JagVillHaVaccin/blob/master/scrapers/vgr.py). @marcusosterberg, I'd love to have the next available time in an upcoming release! 😊

As you can see [here](https://twitter.com/PierreMesure/status/1399628993628983298), this is really useful to make sure that no vaccine spot is lost.
